### ISSUE TITLE
Error on Build - Failed to install the following Android SDK packages as some licences have not been accepted

### ISSUE THREAD

**Issue by KrishnaVyshak** [Nethical-org/Stif#2]
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
     platforms;android-29 Android SDK Platform 29
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by RealNethical** [comment]
I think something is wrong with ur android studio

**Comment by RealNethical** [comment]
Ok ok
I fixed the issue 
I will commit soon

**Comment by RealNethical** [comment]
Ok problem is now fixed
